### ISSUE TITLE
JoVE video tutorial link missing

### ISSUE THREAD

**Issue by ifed3** [emernic/OT2_MoClo_JoVE#1]
Hi @emernic, can you provide a link for the video referenced in Step 4 of the general installation?

**Comment by emernic** [comment]
Hey, sorry for the confusion. The video doesn't actually exist yet. This project is still a work in progress. I would contact Samuel Oliveira (smdo@bu.edu) from the DAMP Lab if you are looking for help getting this working. I am no longer at the DAMP Lab, but I believe they are still actively working on this project.

**Comment by ifed3** [comment]
Alright good to know. Thanks for getting back so quickly!
